accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import Gust_login
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('delete_confirm', TemplateView.as_view(template_name='registration/delete_confirm.html'), name='delete-confirmation'),
    path('delete_complete', views.DeleteView.as_view(), name='delete-complete'),
    path('gust_login', Gust_login, name='gust_login'),
]

analysis/urls.py
from django.urls import path
from . import views

app_name = 'analysis'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('company/<int:pk>', views.CompanyView.as_view(), name='company'),
    path('statement_detail/<int:pk>', views.StatementView.as_view(), name='statement'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from .settings import base, local

urlpatterns = [
    path('', include('analysis.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(local.STATIC_URL, 
document_root=local.STATIC_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja" class="h-100">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/> 
        <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" 
            integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}"/>
        {% block customcss %}
        {% endblock customcss %}
        <title>Company Analysis</title>
    </head>
    <body>
        <div class="d-flex flex-column flex-md-row align-items-center p-4 px-md-5 bg-dark shadow-sm ">
            <h2 class=" my-0 mr-md-auto font-weight-bold"><a href="{% url 'analysis:index' %}" class="site_name">Company Analysis</a></h2>
            <nav class="my-2 my-md-0 mr-md-3">
                {% if user.is_authenticated %}
                    <a class="btn btn-outline-light btn-lg mr-2" href="{% url 'accounts:profile' %}">マイページ</a>
                    <a class="btn btn-outline-light btn-lg" href="{% url 'logout' %}">ログアウト</a>
                {% endif %}
            </nav>
        </div>
        <div class="image-box">
        </div>
        <div class="container mt-3">
            {% block body %}
            {% endblock body%}
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
                crossorigin="anonymous"></script>
    </body>
</html>

templates/base_centered.html
{% extends "base.html" %}

{% block body %}
    
    <div class="row text-center">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">

                    {% block content %}{% endblock %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% load bootstrap4 %}


{% block body %}
    {% if user.is_authenticated %}
        <script>
            jQuery(function($){
                $.extend( $.fn.dataTable.defaults, {
                    language: {
                        url: "https://cdn.datatables.net/plug-ins/1.10.21/i18n/Japanese.json"
                        }
                        });
                $("#statement_list").DataTable({
                    "searching": true,
                    "paging":   true,
                    "ordering": true,
                    "lengthChange": true,
                    
                    }).columns.adjust().draw();
                });
        </script>
        <h1 class="index-top font-weight-bold">日経平均の採用企業リスト</h1>
        <table id="statement_list" width="100%" class="table table-bordered item-felid">
            <thead>
            <tr>
                <th class="text-center item-list" width="30%">業界</th>
                <th class="text-center item-list" width="20%">証券コード</th>
                <th class="text-center item-list">会社</th>
            </tr>
            </thead>
            <tbody>
            {% for item in company_list %}
            <tr class="odd gradeX text-center">
                <td class="text-center">{{ item.industry }}</td>
                <td class="text-center"><a href="{% url 'analysis:company' item.pk %}">{{ item.code }}</a></td>
                <td><a href="{% url 'analysis:company' item.pk %}">{{ item.name }}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="description">
            <div class="web-description ">
                <h1 class="font-weight-bold">投資に役立つ財務分析</h1>
                <p class="font-weight-bold">日経平均に採用された企業の財務分析を提供するサービスです</p>
            </div>
            <div class="registration-login">
                <a class="btn btn-outline-light btn-success btn-lg mr-2" href="{% url 'login' %}">ログイン</a>
                <a class="btn btn-outline-light btn-info btn-lg mr-2" href="{% url 'accounts:signup' %}">新規登録</a>
            </div>
            <br>
            <div class="gest-login">
                <a class=" btn btn-primary btn-lg admin_login " rel="nofollow" deta-method="post" href="{% url 'accounts:gust_login' %}" >ゲストログイン</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/top.html
{% extends "base.html" %}

{% block body %}
    <script>
        jQuery(function($){
            $.extend( $.fn.dataTable.defaults, {
                language: {
                    url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
                    }
                    });
            $("#statement_list").DataTable({
                "searching": true,
                "paging":   true,
                "ordering": true,
                "lengthChange": true,
                
                }).columns.adjust().draw();
            });
    </script>
    <h1>トップページ</h1>

    <table id="statement_list" width="100%" class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center" width="40%">会社</th>
            {% comment %} <th class="text-center" width="40%">決算日</th> {% endcomment %}
            <th class="text-center">LINK</th>
        </tr>
        </thead>
        <tbody>
        {% for item in company_list %}
        <tr class="odd gradeX text-center">
            <td class="text-center"><a href="{% url 'analysis:company' item.pk %}">{{ item.name }}</a></td>
            {% comment %} <td class="text-center">{{ item.fiscal_year }}</td>{% endcomment %}
            <td><a href="{% url 'analysis:statement' item.pk %}">詳細へ</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}